### PR TITLE
update readme and make default label trello instead of test-case

### PR DESCRIPTION
**Pull request by pwright**
some updates to readme, 
and I wanted to avoid creating label test-case on all jira (as a quick fix, I changed it to 'trello' but wonder whether if should be set in '~/.trira'. 
Great job, I can see this being very useful to me

### CODE REVIEW

**Comment by kpiwko** [comment]
Sorry @finp - github notifications being discarded. I wonder how to fix default label - this is obviously something we should externalize.

**Comment by trepel** [comment]
Hi @finp 
if you remove the sync.js modifications - I plan to parametrize this soon - I will try to merge this PR

**Review by trepel — CHANGES_REQUESTED** [review]
Please remove the modifications done for sync.js file. I plan to fix it differently (using command line parameter instead of hard-coded value). I will merge the PR then.

**Comment by pwright** [comment]
closing in preparation of repo move

**Pull request closed without merging**
