### PR TITLE
added prefix support for generating jira tickets from trello cards

### PR DESCRIPTION
**Pull request by pawelpaszki**
## Motivation
https://issues.jboss.org/browse/INTLY-876

## Verification Steps
Run this command (which will not create the Jira tickets, but will print what would the created tickets look like (--dry-run). Note - you need to have access to RHMAP test plan on Trello and also have trira set up locally (trello env vars):

```
trira sync 'Test Plan: Self Managed' 'RHMAP-21801'  --add-labels=team-customer-success,test-case --list-regexp 'MUST PER BUILD' --dry-run --prefix='PDS '
```

## Checklist:

- [x] Code has been tested locally by PR requester

## Progress

- [x] Finished task

### CODE REVIEW

**Comment by trepel** [comment]
@pawelpaszki 

I haven't tried but looks good. Few things tough:
1) could you please update readme (optional)
2) please add the `prefix` parameter somewhere here as well: https://github.com/aerogear/trira/blob/master/cmd/sync.js#L37
3) make sure that `trira help sync` will output the nice description of the `prefix` param (this will probably be done as part of 2) anyway

**Review by trepel — CHANGES_REQUESTED** [review]
See my comment

**Comment by pawelpaszki** [comment]
@trepel done

**Comment by trepel** [comment]
@pawelpaszki thanks, the code looks good to me now. I will give it a try and if all works as expected I will approve and merge.

**Review by trepel — APPROVED** [review]
Works as expected, approving & merging.

**Pull request merged**
